version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always

    cap_add: 
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: "Europe/Berlin"
      VIRTUAL_HOST: "pihole.home"
      # WEBPASSWORD: 'will be generated random'
    volumes:
      - './data/etc-pihole/:/etc/pihole/'
      - './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    network_mode: host
    networks:
      network:
        ipv4_address: 172.22.0.2

networks:
  network:
    ipam:
      config:
        - subnet: 172.22.0.0/24
