version: '3'

services:
  db:
    image: postgres:10
    container_name: mayan-db
    restart: always
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayan
      POSTGRES_USER: mayan
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 172.23.0.3

  mayan:
    image: mayanedms/mayanedms:3
    container_name: mayan
    depends_on:
      - db
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayan
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_CONN_MAX_AGE: 60
    volumes:
      - ./data/mayan/scanned_files:/srv/scanned_files
      - ./data/mayan/watch_folder:/srv/watch_folder
      - ./data/mayan/media:/var/lib/mayan
#    ports:
#      - 80:8000 # Web
    networks:
      network:
        ipv4_address: 172.23.0.2

networks:
  network:
    ipam:
      config:
        - subnet: 172.23.0.0/24